name: integtaion-tests

on:
  pull_request:
    #TODO change it when release
    branches: [ "feature/v2" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CHAIN_DATA: ${{github.workspace}}/chain-data/v1/chain 
    steps:
      - name: "print context"
        run: echo ${{github.event.pull_request.title}}
      - name: "get branch config"
        run: echo "TEST_WITH=$(echo ${{ github.event.pull_request.title }} | awk -F'[}{]' '{print $2}' | sed 's/ *$//g')" >> $GITHUB_ENV
      - name: "print TEST_WITH"
        run: echo ${{env.TEST_WITH}}
      - name: "check TEST_WITH"
        if: ${{env.TEST_WITH == ''}}
        run: exit 1
      - name: "copy chain test data"
        uses: actions/checkout@v3
        with:
          repository: "ruslanglaznyov/test-releases"
          path: "chain-data"
          lfs: true
      - name: "clone chain repo"
        uses: actions/checkout@v3
        with:
          repository: "KYVENetwork/chain"
          path: "chain"
          ref: ${{env.TEST_WITH}}
      - name: "install go"
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: "install ignite"
        run: curl https://get.ignite.com/cli@v0.22.0! | bash
      - name: "build binary"
        run: go build -o chaind cmd/kyved/main.go
        working-directory: ./chain
      - name: set chain path 
        run: |
          echo "COSMOS_BINARY=$(echo ${{github.workspace}}/chain/chaind)" >> $GITHUB_ENV
      - name: Print COSMOS_BINARY
        run: echo $COSMOS_BINARY
      - name: "checkout"
        uses: actions/checkout@v3
        with:
          path: "sdk"
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependency
        run: yarn install
        working-directory: ./chain/test
      - name: "print branch name"
        run: echo ${{ github.event.pull_request.head.ref }}
      - name:  install current branch sdk as dependency for integration tests
        run: yarn add https://github.com/${{ github.repository }}#${{ github.event.pull_request.head.ref }}
        working-directory: ./chain/test
      - name: check package.json
        run: cat package.json
        working-directory: ./chain/test
      - name: run tests
        run: yarn test
        working-directory: ./chain/test


