name: integtaion-tests

on:
  pull_request:
    #TODO change it when release
    branches: [ "feature/v2" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      COSMOS_BINARY: "${{github.workspace}}/releases/integration-tests/chaind"
      COSMOS_DATA: "${{github.workspace}}/releases/integration-tests/chain"
    steps:
      - name: "print context"
        run: echo ${{github.event.pull_request.title}}
      - name: "get branch config"
        run: echo "TEST_WITH=$(echo ${{ github.event.pull_request.title }} | awk -F'[}{]' '{print $2}' | sed 's/ *$//g')" >> $GITHUB_ENV
      - name: "print var"
        run: echo ${{env.TEST_WITH}}
      - name: "check TEST_WITH"
        if: ${{env.TEST_WITH == ''}}
        run: exit 1
      - name: "copy releases"
        uses: actions/checkout@v3
        with:
          repository: "ruslanglaznyov/test-releases"
          path: "releases"
          lfs: true
      - name: 'set cosmos vars '
        run: |
          echo "COSMOS_BINARY=$(echo ${{github.workspace}}/releases/${{env.TEST_WITH}}/chaind)" >> $GITHUB_ENV
          echo "COSMOS_DATA=$(echo ${{github.workspace}}/releases/${{env.TEST_WITH}}/chain)" >> $GITHUB_ENV
      - name: "Check file existence"
        uses: andstor/file-existence-action@v1
        with:
          files: ${{env.COSMOS_BINARY}}
          allow_failure: true
      - name: "clone chain repo"
        uses: actions/checkout@v3
        with:
          repository: "KYVENetwork/chain"
          path: "chain"
          ref: ${{env.TEST_WITH}}
      - name: "checkout"
        uses: actions/checkout@v3
        with:
          path: "sdk"
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependency
        run: yarn install
        working-directory: ./chain/test
      - name: run tests
        run: yarn test
        working-directory: ./chain/test


