name: unit-tests

on:
  push:
    #TODO change it when release
    branches: [ "feature/v2" ]
  pull_request:
    #TODO change it when release
    branches: [ "feature/v2" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]
    steps:
      - name: "checkout chain repo"
        uses: actions/checkout@v3
        with:
          name: "KYVENetwork/chain"
          #TODO checkout to the current realise branch
          ref: "v0.6.0"
      - name: "nodejs install"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: "dependency install"
        working-directory: ./test
        run: yarn install --frozen-lockfile
        #TODO add current branch as dependency
      - name: "run tests"
        working-directory: ./test
        run: yarn test
