name: integtaion-tests

on:
  push:
    #TODO change it when release
    branches: [ "feature/v2" ]
  pull_request:
    #TODO change it when release
    branches: [ "feature/v2" ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: "checkout chain repo"
        uses: actions/checkout@v3
        with:
          name: "KYVENetwork/chain"
          path: "chain"
#          #TODO checkout to the current realise branch
#          ref: "v0.6.0"
      - name: "Show Working directory"
        run: ls chain
      - name: "nodejs install"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: ./chain/test/yarn.lock
          cache: 'yarn'
      - name: "dependency install"
        working-directory: './chain/test'
        run: yarn install --frozen-lockfile
        #TODO add current branch as dependency
      - name: "run tests"
        working-directory: './chain/test'
        run: yarn test
